//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buildeeji.Models.BuildeejiDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuilderDetail
    {
        public int BuilderID { get; set; }
        public string BuilderName { get; set; }
        public string BuilderCompanyName { get; set; }
        public string BuilderPropertyImageName { get; set; }
        public string BuilderAddress { get; set; }
        public Nullable<int> BuilderAddressPin { get; set; }
        public Nullable<int> BuilderPhone { get; set; }
        public Nullable<int> BuilderMobile { get; set; }
        public string BuilderEmail { get; set; }
        public string BuilderCity { get; set; }
        public string BuilderDesc { get; set; }
        public Nullable<int> BuilderDisplayPriority { get; set; }
        public string LanguageCulture { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
