//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buildeeji.Models.BuildeejiDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BuildeejiEntities : DbContext
    {
        public BuildeejiEntities()
            : base("name=BuildeejiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuilderDetail> BuilderDetails { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<PropertyAmenity> PropertyAmenities { get; set; }
        public virtual DbSet<PropertyAvailability> PropertyAvailabilities { get; set; }
        public virtual DbSet<PropertyCategory> PropertyCategories { get; set; }
        public virtual DbSet<PropertyDetail> PropertyDetails { get; set; }
        public virtual DbSet<PropertyIMageCategory> PropertyIMageCategories { get; set; }
        public virtual DbSet<PropertyIMage> PropertyIMages { get; set; }
        public virtual DbSet<PropertyListingType> PropertyListingTypes { get; set; }
        public virtual DbSet<PropertySubCategory> PropertySubCategories { get; set; }
        public virtual DbSet<PropertyVideo> PropertyVideos { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ServiceCategory> ServiceCategories { get; set; }
        public virtual DbSet<ServiceProviderDetail> ServiceProviderDetails { get; set; }
        public virtual DbSet<ServiceProviderMapping> ServiceProviderMappings { get; set; }
        public virtual DbSet<ServiceSubCategory> ServiceSubCategories { get; set; }
        public virtual DbSet<UnitMeasure> UnitMeasures { get; set; }
        public virtual DbSet<UserLoginDetail> UserLoginDetails { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<WebsiteAdImage> WebsiteAdImages { get; set; }
        public virtual DbSet<WebsiteAdVideo> WebsiteAdVideos { get; set; }
    }
}
