//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buildeeji.Models.BuildeejiDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyDetail
    {
        public int PropertyDetailsId { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public string SubCategory { get; set; }
        public string PropertyAmenityIDs { get; set; }
        public Nullable<int> Bedrroms { get; set; }
        public Nullable<int> Washrooms { get; set; }
        public Nullable<int> Balcony { get; set; }
        public Nullable<int> FloorNUmber { get; set; }
        public Nullable<int> TotalFloors { get; set; }
        public string Commets { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
