//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buildeeji.Models.BuildeejiDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProviderDetail
    {
        public int ServiceProviderID { get; set; }
        public string ServiceProviderName { get; set; }
        public string ServiceProviderCompanyName { get; set; }
        public string ServicePropertyImageName { get; set; }
        public string ServiceProviderAddress { get; set; }
        public Nullable<int> ServiceProviderAddressPin { get; set; }
        public Nullable<int> ServiceProviderPhone { get; set; }
        public Nullable<int> ServiceProviderMobile { get; set; }
        public string ServiceProviderEmail { get; set; }
        public string ServiceProviderCity { get; set; }
        public Nullable<int> ServiceProviderDisplayPriority { get; set; }
        public string ServiceProviderDesc { get; set; }
        public string LanguageCulture { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
